CirclesUBI/o-platform

.dockerignore, .github/workflows/build-container.yml, Dockerfile.ci, build.sh, build_libs.sh, container/container-compose.ci.yaml, package.json, packages/o-editors/src/dropdownItems/DropDownCity.svelte, shell/src/dapps/o-coop/processes/createOrganisation.ts, shell/src/shared/api/data/codegen.yml, shell/src/shared/api/promptCity.ts, shell/src/shared/environment.ts, shell/webpack.config.js
We are adding a container image and an associated build workflow.
Closes #11, from which we inherit other changes in upstream.
=> Add container image and build workflow

.dockerignore, Dockerfile.ci, build.sh, build_libs.sh, container/container-compose.ci.yaml, package.json, packages/o-editors/src/dropdownItems/DropDownCity.svelte, shell/src/dapps/o-coop/processes/createOrganisation.ts, shell/src/shared/api/data/codegen.yml, shell/src/shared/api/promptCity.ts, shell/src/shared/environment.ts, shell/webpack.config.js
Upstream has changes in the build process, which we intend to sync here.
Subsequent PRs will reference this repository directly.
=> Sync dev with upstream

shell/src/dapps/o-marketlisting/pages/MarketlistingDetail.svelte
=> moved vendor-shareButton to the left

packages/o-events/src/eventTypes.ts, shell/src/dapps/o-onboarding/processes/registration/promptRegistration.ts, shell/src/dapps/o-passport/processes/upsertIdentity.ts, shell/src/shared/api/data/schema.graphql, shell/src/shared/api/data/src/mutations.graphql, shell/src/shared/api/data/types.ts, shell/src/shared/molecules/DappFrame.svelte, shell/src/shared/molecules/DropDown.svelte
**Prerequisite: https://github.com/CirclesUBI/api-server/pull/63**
this adds the SurveydataSessionId to the profile on first Registration.
It also checks if that sessionId is set, and if not, redirects back to the survey.
=> add SurveyData to Profile, validate on first Registration.

shell/src/dapps/o-contacts/pages/Profile.svelte, shell/src/dapps/o-marketlisting/pages/MarketlistingDetail.svelte
Market-Picture a little smaller on big Screens
=> removed 0-padding at Profile

readme.md
=> removing the test, trying with only branch name now

.gitignore, shell/src/dapps/o-passport.manifest.ts, shell/src/dapps/o-passport/pages/Home.svelte, shell/src/dapps/o-passport/pages/UpsertBusiness.svelte
At least in a way that there is some kind of visual response to when adding a new shop
=> squeeze the upsertbusiness for testing perparation

build.sh
We need new container images for `next` including the below commit.
Merging this will create them.
=> Release `dev` to `next`

packages/o-circles/src/safe/gnosisSafeProxy.ts, shell/public/redirect.html, shell/src/dapps/o-banking/atoms/TransactionCard.svelte, shell/src/dapps/o-dashboard/atoms/DashboardColorCard.svelte, shell/src/dapps/o-notifications/atoms/ContactCard.svelte, shell/src/dapps/o-passport/atoms/AccountCard.svelte, shell/src/shared/atoms/ItemCard.svelte, shell/src/shared/atoms/UserImage.svelte, shell/src/shared/molecules/DappFrame.svelte
=> Adjust Dashboard Cards, also fix deprecated substr function

shell/src/dapps/o-passport/processes/upsertIdentity.ts
=> Make location Mandatory for new users

shell/src/dapps/o-banking.manifest.ts, shell/src/dapps/o-contacts.manifest.ts, shell/src/dapps/o-coop.manifest.ts, shell/src/dapps/o-dashboard.manifest.ts, shell/src/dapps/o-homepage.manifest.ts, shell/src/dapps/o-marketlisting.manifest.ts, shell/src/dapps/o-notification.manifest.ts, shell/src/dapps/o-passport.manifest.ts
=> Change support number to: +6281337303696

shell/package.json, shell/src/iShell.ts, shell/src/main.ts, shell/src/shared/environment.ts
added bip39 to window.o for usage from the console.
=> added more mock keys for the use in local environments.

shell/src/dapps/o-marketlisting/models/openingHourWeek.ts
=> Fix OpeningHours Trailing 0s

shell/src/dapps/o-contacts/atoms/ContactCard.svelte, shell/src/dapps/o-contacts/pages/Contacts.svelte, shell/src/shared/environment.ts, shell/src/shared/molecules/DappFrame.svelte, shell/src/shared/molecules/Lists/EventList.svelte, shell/src/shared/molecules/Lists/List.svelte, shell/src/shared/stores/contacts.ts, shell/src/shared/stores/inbox.ts, shell/src/shared/stores/myTransactions.ts, shell/src/shared/stores/pagedEventQuery.ts
APP-109: Trust status doesn't change after trusting
=> APP-105: Notification area doesn't auto-update

shell/src/dapps/o-banking.manifest.ts, shell/src/dapps/o-contacts.manifest.ts, shell/src/dapps/o-coop.manifest.ts, shell/src/dapps/o-dashboard.manifest.ts, shell/src/dapps/o-homepage.manifest.ts, shell/src/dapps/o-marketlisting.manifest.ts, shell/src/dapps/o-notification.manifest.ts, shell/src/dapps/o-passport.manifest.ts
have to test on dev b/c of mobile devices
=> changed whatsapp link

shell/src/dapps/o-marketlisting/pages/MarketlistingDetail.svelte
The button should not be shown in my own detail page
=> Send money shouldn't be shown in own shop

.github/workflows/e2e-pr-tests.yml
This workflow makes the end-to-end tests run in GitHub Actions CI runners.
=> feat/op-69: e2e testing

shell/src/dapps/o-banking.manifest.ts, shell/src/dapps/o-contacts.manifest.ts, shell/src/dapps/o-coop.manifest.ts, shell/src/dapps/o-passport.manifest.ts, shell/src/shared/atoms/ActionListItem.svelte
replaced i18n-window-object with i18n-keys in manifests
inserted Label-component into ActionListItem
=> propper i18n-keys in menues 

shell/src/shared/molecules/NextNav/Components/NavPill.svelte
=> Fix loading spinner and X button not aligned

shell/src/shared/atoms/ItemCard.svelte, shell/src/shared/atoms/UserImage.svelte
=> fix Asset page returns blank

shell/src/dapps/o-survey/components/InformedConsentSecondSurvey.svelte, shell/src/dapps/o-survey/components/UserDataCollectionSurvey.svelte
=> Prevent user for accessing url if consent was not given

shell/src/dapps/o-banking/processes/transfer.ts
=> remove maxFlow check for amount entry step

package.json, shell/src/dapps/o-marketlisting/pages/MarketlistingDetail.svelte
changed opening hours to Bali timezone
APP-410
=> Opening hours don't respect the users' time zone

shell/src/dapps/o-banking/processes/transfer.ts
Reverts CirclesUBI/o-platform#383
=> Revert "remove maxFlow check for amount entry step"

shell/src/dapps/o-marketlisting/pages/MarketlistingDetail.svelte
=> fix clicking the opening hours button crashes if there is no data

shell/src/dapps/o-marketlisting/pages/MarketlistingDetail.svelte
Reverts CirclesUBI/o-platform#427
please follow https://github.com/CirclesUBI/shared-development-organizing/blob/main/circles-indonesia/deploy/o-platform.md
for next deployments, upping the version number and creating a tag etc...
=> Revert "merge dev into next"
